### ISSUE TITLE
Working directory set by `look` ignored by iTerm2 reuse working directory feature

### ISSUE THREAD

**Issue by mickamy** [motemen/ghq#189]
iTerm2 provides `Reuse working directory` feature.
But it would be not working when we change directory by `ghq look <repo>` somehow.
I can confirm that it is working fine when we change directory with `cd` command.
Any thoughts on this?

**Comment by mlavi** [comment]
@mickamy I read your issue title and had to comment: I also use iTerm2, but I do not have my Mac handy at the moment. However, using ```ghq look``` with version 0.14.0 on Linux (Mint 19.2) for any repository that ghq can reach results in a new shell spawned in the local repository directory.

I suspect you encounter the same behaviour.

I find this problematic because I cannot chain commands with ghq, e.g.:
```ghq look my_repo && git status```

**Comment by Songmu** [comment]
The "ghq look" do "cd" in the child process, so it is difficult to solve this problem. This is similar to do "cd" on screen or tmux.

I close this issue because it is fundamentally difficult to resolve.
