### ISSUE TITLE
Add -i option to specify a private key

### ISSUE THREAD

**Issue by knqyf263** [motemen/ghq#215]
Thank you for this awesome tool!

`ssh` has `-i` option to select a file from which the identity (private key) for public key authentication is read
e.g. ssh -i ~/.ssh/id_rsa_example

Also, `git` can specify `sshCommand`.
e.g. git -c core.sshCommand="ssh -i ~/.ssh/id_rsa_example -F /dev/null" clone ...

Can we add such an option to `ghq`? If yes, I will add the feature. If you think I should use `GIT_SSH_COMMAND` env, I'll close this issue.

**Comment by Songmu** [comment]
Good suggestion!

But, I don't think it is good for `ghq` itself has the option to specify the SSH private key, because there are many environmental differences in the SSH command.

I imagine these environmental differences are the reason even `git` have no specifying private key option, only has options to specify commands to absorb it.

**Comment by knqyf263** [comment]
Thank you for the response.
I see. If `ghq` depends on a pure Go library, we don't have to think of the environmental differences so much, but it seems difficult for now.

**Comment by Songmu** [comment]
Thank you.
As you say, if the git and ssh commands are not reinvented with Go, full support seems to be difficult. Of course, I know that Go has that potential.
