### ISSUE TITLE
Feature request: add some flag printing the directory path on `ghq create`

### ISSUE THREAD

**Issue by micnncim** [motemen/ghq#247]
Supporting `ghq create` is pretty cool. I've already been a big fan of this feature.

## What

I believe it's good for many developers to print only the created directory path.

An example is here:

```
$ ghq create tmp
Initialized empty Git repository in /Users/micnncim/src/github.com/micnncim/tmp/.git/
/Users/micnncim/src/github.com/micnncim/tmp
$ ghq create tmp --raw-dir
/Users/micnncim/src/github.com/micnncim/tmp
```

The printed directory is from https://github.com/motemen/ghq/blob/master/cmd_create.go#L27.

I'm not sure what name is good for the flag (`--raw-dir` is just an idea as the example).

If this idea looks good, I'm willing to implement the feature :)

## Why

If the flag is supported, we can create a helpful script such as `ghq create --raw-dir | cd -` meaning immediate `cd` to the created directory.

**Comment by Songmu** [comment]
You can already do what you want, and it is designed behavior. Please try the following.

```console
% cd $(ghq create hogege)
```

Because "ghq create" outputs only the directory path to STDOUT. Other outputs are printed to STDERR, not STDOUT.

If you feel the log outputs noisy, it may be good to implement some new options for suppressing log output like "--silent". The "curl" and etc. has such behavior.

**Comment by micnncim** [comment]
I didn't notice the fact. It works as I hope. Thank you for your reply and advice :+1:
